version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=db_user
      - DB_PASS=super_awesome_password
      - DB_NAME=database

  database:
    image: postgres
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=super_awesome_password
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

  flyway:
    image: flyway/flyway:latest
    command: migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://database:5432/database
      - FLYWAY_USER=db_user
      - FLYWAY_PASSWORD=super_awesome_password
    depends_on:
      database:
        condition: service_healthy
